// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi5LOFSe_jONZiRi-M_rTod3ITNo0Txdc',
    appId: '1:469673837156:web:beae368c7f7aabf3acd571',
    messagingSenderId: '469673837156',
    projectId: 'resume-builder-b3429',
    authDomain: 'resume-builder-b3429.firebaseapp.com',
    databaseURL: 'https://resume-builder-b3429-default-rtdb.firebaseio.com',
    storageBucket: 'resume-builder-b3429.firebasestorage.app',
    measurementId: 'G-DK5Z6XKG6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXMTzTD41E-r6ddFuIk2QF4hX6nPHwds',
    appId: '1:469673837156:android:a67588186a6482e6acd571',
    messagingSenderId: '469673837156',
    projectId: 'resume-builder-b3429',
    databaseURL: 'https://resume-builder-b3429-default-rtdb.firebaseio.com',
    storageBucket: 'resume-builder-b3429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCIqlxZClbDYPpxtyhmImCqDWbtiawvI',
    appId: '1:469673837156:ios:3ce25b737922d242acd571',
    messagingSenderId: '469673837156',
    projectId: 'resume-builder-b3429',
    databaseURL: 'https://resume-builder-b3429-default-rtdb.firebaseio.com',
    storageBucket: 'resume-builder-b3429.firebasestorage.app',
    iosBundleId: 'com.example.craftfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYCIqlxZClbDYPpxtyhmImCqDWbtiawvI',
    appId: '1:469673837156:ios:3ce25b737922d242acd571',
    messagingSenderId: '469673837156',
    projectId: 'resume-builder-b3429',
    databaseURL: 'https://resume-builder-b3429-default-rtdb.firebaseio.com',
    storageBucket: 'resume-builder-b3429.firebasestorage.app',
    iosBundleId: 'com.example.craftfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi5LOFSe_jONZiRi-M_rTod3ITNo0Txdc',
    appId: '1:469673837156:web:9c11700c3221f1c3acd571',
    messagingSenderId: '469673837156',
    projectId: 'resume-builder-b3429',
    authDomain: 'resume-builder-b3429.firebaseapp.com',
    databaseURL: 'https://resume-builder-b3429-default-rtdb.firebaseio.com',
    storageBucket: 'resume-builder-b3429.firebasestorage.app',
    measurementId: 'G-1MXWYKJ0JY',
  );
}
